### PR TITLE
Iss65: Restore deleted setup script

### PR DESCRIPTION
**Pull request by JeremyMcCormick**
Merge PR #63 before this.

### CODE REVIEW

**Comment by omar-moreno** [comment]
Can you split the GDML fix and scripts directory issue into two different
pull request?

Also, I have found that the env script is never used and becomes annoying
to maintain.  Is there a reason you feel it's needed?

**Comment by JeremyMcCormick** [comment]
> Can you split the GDML fix and scripts directory issue into two different pull request?

See the comments.  You can merge #63 to get only the GDML lib fix.  I merged it into this branch as I couldn't compile otherwise to check the script.

> Also, I have found that the env script is never used and becomes annoying to maintain. Is there a reason you feel it's needed?

The automatically generated setup script is used by me *all the time* in multiple environments (SLAC, JLab, my laptop, etc.), and it has been stable for months with the exception of a few minor updates.  If it isn't in the repository, I have to write a new setup script in every different environment, which actually is far more annoying.  So please approve it.  It does no harm to have it in there even if you personally don't plan to use it, and I will make sure it is kept up to date if there are any changes needed.

**Comment by JeremyMcCormick** [comment]
> Can you split the GDML fix and scripts directory issue into two different
pull request?

Are you seriously worried about this given that you just completely reorganized the repository without even referencing a github issue?  ;-)

Anyways, do #63 first and then this one and all should be well.

**Comment by omar-moreno** [comment]
On Tue, Mar 19, 2019, 11:28 PM Jeremy McCormick <notifications@github.com>
wrote:

> Can you split the GDML fix and scripts directory issue into two different
> pull request?
>
> Are you seriously worried about this given that you just completely
> reorganized the repository without even referencing a github issue? ;-
>
Yes.

**Review by cbravo135 — APPROVED** [review]

**Pull request merged**
